flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0;
        policy drop;

        # allow loopback
        iif "lo" accept

         # drop invalid packets
        ct state invalid drop

        # drop spoofed private addresses these ranges SHOULD NOT appear from outside networks
        ip saddr { 10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12 } drop


        # allow established connections
        ct state established,related accept

        # allow ICMP
        ip protocol icmp limit rate 10/second accept
        ip6 nexthdr icmpv6 limit rate 10/second accept

        # allow ssh but implement rate limiting to stop brute force attacks:
        tcp dport 22 ct state new limit rate 10/minute accept

        # allow ssh (IPv4 + IPv6) with rate limiting
        tcp dport 22 ct state new limit rate 10/minute accept

        
        # allow ICMPv6 (rate limited)
        ip6 nexthdr icmpv6 limit rate 10/second accept

        # allow IPv6 neighbour discovery (required for IPv6 networking)
        ip6 nexthdr icmpv6 icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-advert } accept

        # allow http/https (IPv4 + IPv6)
        tcp dport { 80, 443 } ct state new accept

        # log dropped packets
        log prefix "FIREWALL DROP: " drop

    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}