flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0;
        policy drop;

        # allow loopback
        iif "lo" accept

        # drop spoofed private addresses these ranges SHOULD NOT appear from outside networks
        ip saddr { 10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12 } drop

        # drop invalid packets
        ct state invalid drop

        # allow established connections
        ct state established,related accept

        # allow ICMP
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

        # allow ssh but implement rate limiting to stop brute force attacks:
        tcp dport 22 ct state new limit rate 10/minute accept

        # allow http/https
        tcp dport { 80, 443 } accept

        # log dropped packets
        log prefix "FIREWALL DROP: " drop

    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}